[log_connections]
command:/usr/local/opnsense/scripts/netshield/connection_logger.py
parameters:
type:script_output
message:Process new DNS connection logs

[get_sessions]
command:/usr/local/opnsense/scripts/netshield/get_sessions.py
parameters:%s
type:script_output
message:Get session data

[get_session_stats]
command:/usr/local/opnsense/scripts/netshield/get_session_stats.py
parameters:
type:script_output
message:Get session statistics for today

[purge_sessions]
command:/usr/local/opnsense/scripts/netshield/purge_sessions.py
parameters:%s
type:script_output
message:Purge old session records

[manage_session_block]
command:/usr/local/opnsense/scripts/netshield/manage_session_block.py
parameters:%s
type:script_output
message:Managing session block
