"""
SPDX-License-Identifier: BSD-2-Clause

Copyright (c) 2024 NetShield Contributors
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

NetShield config.py — INI config reader + OPNsense config.xml helper.
"""

import configparser
import logging
import os
import re
import subprocess
import threading
import xml.etree.ElementTree as ET
from typing import Optional

log = logging.getLogger(__name__)

NETSHIELD_CONF = "/usr/local/etc/netshield.conf"
OPNSENSE_CONFIG_XML = "/conf/config.xml"


class Config:
    """
    Singleton config reader for /usr/local/etc/netshield.conf (INI format).

    The file is generated by OPNsense's template engine from the NetShield
    model XML; never edit it by hand.
    """

    _instance: Optional["Config"] = None
    _lock = threading.Lock()

    def __new__(cls) -> "Config":
        with cls._lock:
            if cls._instance is None:
                instance = super().__new__(cls)
                instance._parser = configparser.ConfigParser(
                    interpolation=None,
                    default_section="DEFAULT",
                )
                instance._conf_path = NETSHIELD_CONF
                instance._loaded = False
                instance._rlock = threading.RLock()
                cls._instance = instance
        return cls._instance

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _ensure_loaded(self) -> None:
        with self._rlock:
            if not self._loaded:
                self._load()

    def _load(self) -> None:
        """(Re)load the INI file from disk."""
        path = self._conf_path
        if not os.path.isfile(path):
            log.warning("Config file not found: %s — using empty config", path)
            self._parser.read_dict({})
            self._loaded = True
            return
        try:
            self._parser.clear()
            read_ok = self._parser.read(path, encoding="utf-8")
            if read_ok:
                log.debug("Loaded config from %s", path)
            else:
                log.warning("Config file could not be read: %s", path)
            self._loaded = True
        except configparser.Error as exc:
            log.error("Failed to parse config %s: %s", path, exc)
            self._loaded = True  # Mark loaded so we don't loop on error

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def reload(self) -> None:
        """Force reload of config from disk."""
        with self._rlock:
            self._loaded = False
            self._load()

    def get(self, section: str, key: str, default: Optional[str] = None) -> Optional[str]:
        """Return string value from [section] key, or default."""
        self._ensure_loaded()
        try:
            return self._parser.get(section, key)
        except (configparser.NoSectionError, configparser.NoOptionError):
            return default

    def getboolean(self, section: str, key: str, default: bool = False) -> bool:
        """Return boolean value. Accepts 1/0, yes/no, true/false, on/off."""
        self._ensure_loaded()
        try:
            return self._parser.getboolean(section, key)
        except (configparser.NoSectionError, configparser.NoOptionError):
            return default
        except ValueError as exc:
            log.warning("getboolean %s/%s: %s — returning default %s", section, key, exc, default)
            return default

    def getint(self, section: str, key: str, default: int = 0) -> int:
        """Return integer value."""
        self._ensure_loaded()
        try:
            return self._parser.getint(section, key)
        except (configparser.NoSectionError, configparser.NoOptionError):
            return default
        except ValueError as exc:
            log.warning("getint %s/%s: %s — returning default %d", section, key, exc, default)
            return default

    def sections(self) -> list:
        """Return all section names."""
        self._ensure_loaded()
        return self._parser.sections()

    def has_section(self, section: str) -> bool:
        self._ensure_loaded()
        return self._parser.has_section(section)

    def items(self, section: str) -> list:
        """Return (key, value) pairs for a section."""
        self._ensure_loaded()
        try:
            return self._parser.items(section)
        except configparser.NoSectionError:
            return []


# Module-level singleton accessor
def get_config() -> Config:
    """Return the global Config singleton."""
    return Config()


# ------------------------------------------------------------------
# OPNsense config.xml helpers
# ------------------------------------------------------------------

def load_config_xml(path: str = OPNSENSE_CONFIG_XML) -> Optional[ET.Element]:
    """
    Parse OPNsense config.xml and return the root Element.
    Returns None on error.
    """
    if not os.path.isfile(path):
        log.warning("OPNsense config.xml not found at %s", path)
        return None
    try:
        tree = ET.parse(path)
        return tree.getroot()
    except ET.ParseError as exc:
        log.error("Failed to parse config.xml: %s", exc)
        return None


def get_netshield_model(root: Optional[ET.Element] = None) -> Optional[ET.Element]:
    """
    Return the <netshield> element from OPNsense config.xml, if present.
    """
    if root is None:
        root = load_config_xml()
    if root is None:
        return None
    # OPNsense stores plugin models under <OPNsense><NetShield>
    ns_elem = root.find(".//OPNsense/NetShield")
    if ns_elem is None:
        log.debug("No NetShield model found in config.xml")
    return ns_elem


def get_dhcp_staticmaps(root: Optional[ET.Element] = None) -> list:
    """
    Parse DHCP static mappings from config.xml.
    Returns list of dicts with keys: mac, ipaddr, hostname, descr.
    """
    if root is None:
        root = load_config_xml()
    if root is None:
        return []

    results = []
    # Static maps live under <dhcpd><interface><staticmap>
    for iface_elem in root.findall(".//dhcpd/"):
        for smap in iface_elem.findall("staticmap"):
            mac_elem = smap.find("mac")
            ip_elem = smap.find("ipaddr")
            host_elem = smap.find("hostname")
            descr_elem = smap.find("descr")
            if mac_elem is None or ip_elem is None:
                continue
            results.append(
                {
                    "mac": (mac_elem.text or "").strip().lower(),
                    "ipaddr": (ip_elem.text or "").strip(),
                    "hostname": (host_elem.text or "").strip() if host_elem is not None else "",
                    "descr": (descr_elem.text or "").strip() if descr_elem is not None else "",
                }
            )
    return results


# ------------------------------------------------------------------
# Network helpers
# ------------------------------------------------------------------

_GATEWAY_RE = re.compile(
    r"^(?:default|0\.0\.0\.0)\s+([\d.]+)\s+",
    re.MULTILINE,
)


def get_gateway_ip() -> Optional[str]:
    """
    Parse the default gateway IP from `netstat -rn` output.
    Returns an IPv4 string or None.
    """
    try:
        result = subprocess.run(
            ["/usr/bin/netstat", "-rn", "-f", "inet"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        output = result.stdout
        match = _GATEWAY_RE.search(output)
        if match:
            gw = match.group(1)
            log.debug("Detected default gateway: %s", gw)
            return gw
        log.debug("No default gateway found in netstat -rn output")
        return None
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        log.warning("get_gateway_ip failed: %s", exc)
        return None
