"""
SPDX-License-Identifier: BSD-2-Clause

Copyright (c) 2024 NetShield Contributors
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

NetShield dns_filter.py — DNS blocking and safe-search via Unbound local-zone directives.
"""

import logging
import os
import subprocess
import tempfile
from typing import List, Optional

log = logging.getLogger(__name__)

# Where we write our Unbound block config (included by Unbound via include: directive)
NETSHIELD_BLOCKS_CONF = "/var/unbound/etc/netshield_blocks.conf"
NETSHIELD_SAFESEARCH_CONF = "/var/unbound/etc/netshield_safesearch.conf"

# Unbound include directory used by OPNsense
UNBOUND_INCLUDE_DIR = "/usr/local/etc/unbound.opnsense.d"
UNBOUND_BLOCKS_LINK = os.path.join(UNBOUND_INCLUDE_DIR, "netshield_blocks.conf")
UNBOUND_SAFESEARCH_LINK = os.path.join(UNBOUND_INCLUDE_DIR, "netshield_safesearch.conf")

# Safe search CNAME targets
_SAFESEARCH_REDIRECTS = {
    # Google
    "google.com":      "forcesafesearch.google.com.",
    "www.google.com":  "forcesafesearch.google.com.",
    # Regional Google domains — add more as needed
    "google.co.uk":    "forcesafesearch.google.com.",
    "google.com.au":   "forcesafesearch.google.com.",
    "google.ca":       "forcesafesearch.google.com.",
    "google.de":       "forcesafesearch.google.com.",
    "google.fr":       "forcesafesearch.google.com.",
    "google.co.in":    "forcesafesearch.google.com.",
    "google.co.jp":    "forcesafesearch.google.com.",
    # YouTube
    "youtube.com":     "restrict.youtube.com.",
    "www.youtube.com": "restrict.youtube.com.",
    "m.youtube.com":   "restrict.youtube.com.",
    # Bing
    "bing.com":        "strict.bing.com.",
    "www.bing.com":    "strict.bing.com.",
}

_HEADER = """\
# NetShield — generated file, do not edit manually.
# Regenerated by netshield dns_filter.py on config change.

"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_domain(domain: str) -> str:
    """Strip wildcards and whitespace; return lowercased FQDN."""
    return domain.lstrip("*.").strip().lower()


def _ensure_dir(path: str) -> bool:
    """Create directory if it does not exist. Returns True on success."""
    if not path:
        return True
    if not os.path.isdir(path):
        try:
            os.makedirs(path, mode=0o755, exist_ok=True)
        except OSError as exc:
            log.error("Cannot create directory %s: %s", path, exc)
            return False
    return True


def _write_atomic(path: str, content: str) -> bool:
    """
    Write content to path atomically using a temp file + rename.
    Returns True on success.
    """
    target_dir = os.path.dirname(path) or "."
    if not _ensure_dir(target_dir):
        return False
    try:
        fd, tmp_path = tempfile.mkstemp(dir=target_dir, prefix=".ns_tmp_")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
            os.replace(tmp_path, path)
        except Exception:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
        return True
    except OSError as exc:
        log.error("Failed to write %s: %s", path, exc)
        return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_block_config(domains: List[str]) -> str:
    """
    Generate Unbound local-zone NXDOMAIN directives for a list of domains.
    Wildcards (*.example.com) are supported — we add both the bare domain
    and a wildcard local-data response.

    Returns the config file content as a string (does not write to disk).
    """
    lines = [_HEADER]
    seen = set()
    for raw in domains:
        domain = _safe_domain(raw)
        if not domain or domain in seen:
            continue
        seen.add(domain)
        # Unbound: local-zone "domain." always_nxdomain
        lines.append(f'local-zone: "{domain}." always_nxdomain')
    lines.append("")
    return "\n".join(lines)


def generate_safe_search_config() -> str:
    """
    Generate Unbound CNAME redirect config for safe search enforcement.
    Returns config content as a string.
    """
    lines = [_HEADER]
    for domain, cname_target in sorted(_SAFESEARCH_REDIRECTS.items()):
        # Use always_nxdomain + local-data CNAME approach
        lines.append(f'local-zone: "{domain}." redirect')
        lines.append(f'local-data: "{domain}. IN CNAME {cname_target}"')
    lines.append("")
    return "\n".join(lines)


def apply_config(
    blocks_content: Optional[str] = None,
    safesearch_content: Optional[str] = None,
) -> bool:
    """
    Write Unbound config files and reload Unbound.

    blocks_content     — output of generate_block_config(), or None to skip
    safesearch_content — output of generate_safe_search_config(), or None to skip

    Returns True if Unbound reload succeeded (or was not needed).
    """
    changed = False

    if blocks_content is not None:
        _ensure_dir(os.path.dirname(NETSHIELD_BLOCKS_CONF))
        if _write_atomic(NETSHIELD_BLOCKS_CONF, blocks_content):
            # Symlink / copy into Unbound include dir
            _ensure_dir(UNBOUND_INCLUDE_DIR)
            _install_conf(NETSHIELD_BLOCKS_CONF, UNBOUND_BLOCKS_LINK)
            changed = True

    if safesearch_content is not None:
        _ensure_dir(os.path.dirname(NETSHIELD_SAFESEARCH_CONF))
        if _write_atomic(NETSHIELD_SAFESEARCH_CONF, safesearch_content):
            _ensure_dir(UNBOUND_INCLUDE_DIR)
            _install_conf(NETSHIELD_SAFESEARCH_CONF, UNBOUND_SAFESEARCH_LINK)
            changed = True

    if not changed:
        log.debug("apply_config: nothing to write, skipping Unbound reload")
        return True

    return _reload_unbound()


def _install_conf(src: str, dst: str) -> None:
    """Copy src to dst (create or overwrite). Symlinks can fail on FreeBSD jails."""
    try:
        import shutil
        shutil.copy2(src, dst)
        log.debug("Installed %s -> %s", src, dst)
    except OSError as exc:
        log.warning("Could not install config to %s: %s", dst, exc)


def _reload_unbound() -> bool:
    """
    Ask Unbound to reload its config via unbound-control reload.
    Falls back to service unbound restart if unbound-control is not available.
    Returns True on success.
    """
    for cmd in (
        ["/usr/local/sbin/unbound-control", "reload"],
        ["/usr/sbin/service", "unbound", "reload"],
        ["/usr/local/sbin/unbound-control", "reload_keep_cache"],
    ):
        if not os.path.isfile(cmd[0]):
            continue
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                log.info("Unbound reloaded via %s", " ".join(cmd))
                return True
            log.warning(
                "Unbound reload command %s returned %d: %s",
                cmd, result.returncode, result.stderr.strip()
            )
        except (subprocess.TimeoutExpired, OSError) as exc:
            log.warning("Unbound reload command %s failed: %s", cmd, exc)

    log.error("Could not reload Unbound — no working reload command found")
    return False


def get_blocked_domain_count(path: str = NETSHIELD_BLOCKS_CONF) -> int:
    """
    Count the number of blocked domains in the current block config file.
    Returns 0 if the file does not exist or cannot be read.
    """
    if not os.path.isfile(path):
        return 0
    count = 0
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                stripped = line.strip()
                if stripped.startswith("local-zone:") and "always_nxdomain" in stripped:
                    count += 1
    except OSError as exc:
        log.warning("get_blocked_domain_count: %s", exc)
    return count
