#!/usr/local/bin/python3
"""OUI (MAC vendor) lookup and device category auto-detection for NetShield."""

# MAC OUI prefix -> (vendor_name, device_category)
# Categories: cameras, desktops, gaming_consoles, iot, laptops, mobiles,
#             multimedia, network, printers, servers, smart_glasses,
#             smart_watches, tvs, vehicles, voip, other
#
# This is a curated mapping of common OUI prefixes to device types.
# Covers 500+ most common vendors seen on home/office networks.

OUI_VENDOR_MAP = {
    # Apple devices
    "00:03:93": ("Apple", "mobiles"),
    "00:05:02": ("Apple", "mobiles"),
    "00:0A:27": ("Apple", "mobiles"),
    "00:0A:95": ("Apple", "mobiles"),
    "00:0D:93": ("Apple", "mobiles"),
    "00:10:FA": ("Apple", "mobiles"),
    "00:11:24": ("Apple", "mobiles"),
    "00:14:51": ("Apple", "mobiles"),
    "00:16:CB": ("Apple", "mobiles"),
    "00:17:F2": ("Apple", "mobiles"),
    "00:19:E3": ("Apple", "mobiles"),
    "00:1B:63": ("Apple", "mobiles"),
    "00:1C:B3": ("Apple", "mobiles"),
    "00:1D:4F": ("Apple", "mobiles"),
    "00:1E:52": ("Apple", "mobiles"),
    "00:1E:C2": ("Apple", "mobiles"),
    "00:1F:5B": ("Apple", "mobiles"),
    "00:1F:F3": ("Apple", "mobiles"),
    "00:21:E9": ("Apple", "mobiles"),
    "00:22:41": ("Apple", "mobiles"),
    "00:23:12": ("Apple", "mobiles"),
    "00:23:32": ("Apple", "mobiles"),
    "00:23:6C": ("Apple", "mobiles"),
    "00:23:DF": ("Apple", "mobiles"),
    "00:24:36": ("Apple", "mobiles"),
    "00:25:00": ("Apple", "mobiles"),
    "00:25:4B": ("Apple", "mobiles"),
    "00:25:BC": ("Apple", "mobiles"),
    "00:26:08": ("Apple", "mobiles"),
    "00:26:4A": ("Apple", "mobiles"),
    "00:26:B0": ("Apple", "mobiles"),
    "00:26:BB": ("Apple", "mobiles"),
    "00:3E:E1": ("Apple", "mobiles"),
    "00:50:E4": ("Apple", "mobiles"),
    "00:56:CD": ("Apple", "mobiles"),
    "00:61:71": ("Apple", "mobiles"),
    "00:6D:52": ("Apple", "mobiles"),
    "00:88:65": ("Apple", "mobiles"),
    "00:B3:62": ("Apple", "mobiles"),
    "00:C6:10": ("Apple", "mobiles"),
    "00:CD:FE": ("Apple", "mobiles"),
    "00:DB:70": ("Apple", "mobiles"),
    "00:F4:B9": ("Apple", "mobiles"),
    "00:F7:6F": ("Apple", "mobiles"),
    "04:0C:CE": ("Apple", "mobiles"),
    "04:15:52": ("Apple", "mobiles"),
    "04:26:65": ("Apple", "mobiles"),
    "04:48:07": ("Apple", "mobiles"),
    "04:4B:ED": ("Apple", "mobiles"),
    "04:52:F3": ("Apple", "mobiles"),
    "04:54:53": ("Apple", "mobiles"),
    "04:D3:CF": ("Apple", "mobiles"),
    "04:DB:56": ("Apple", "mobiles"),
    "04:E5:36": ("Apple", "mobiles"),
    "04:F1:3E": ("Apple", "mobiles"),
    "04:F7:E4": ("Apple", "mobiles"),
    "08:00:07": ("Apple", "desktops"),
    "08:66:98": ("Apple", "mobiles"),
    "08:6D:41": ("Apple", "mobiles"),
    "0C:30:21": ("Apple", "mobiles"),
    "0C:3E:9F": ("Apple", "mobiles"),
    "0C:4D:E9": ("Apple", "mobiles"),
    "0C:74:C2": ("Apple", "mobiles"),
    "0C:BC:9F": ("Apple", "mobiles"),
    "10:40:F3": ("Apple", "mobiles"),
    "10:9A:DD": ("Apple", "mobiles"),
    "10:DD:B1": ("Apple", "mobiles"),
    "14:10:9F": ("Apple", "mobiles"),
    "14:20:5E": ("Apple", "mobiles"),
    "14:5A:05": ("Apple", "mobiles"),
    "14:8F:C6": ("Apple", "mobiles"),
    "14:99:E2": ("Apple", "mobiles"),
    "18:20:32": ("Apple", "mobiles"),
    "18:34:51": ("Apple", "mobiles"),
    "18:65:90": ("Apple", "mobiles"),
    "18:9E:FC": ("Apple", "mobiles"),
    "18:AF:61": ("Apple", "mobiles"),
    "18:E7:F4": ("Apple", "mobiles"),
    "18:EE:69": ("Apple", "mobiles"),
    "1C:36:BB": ("Apple", "mobiles"),
    "1C:91:48": ("Apple", "mobiles"),
    "1C:AB:A7": ("Apple", "mobiles"),
    "20:78:F0": ("Apple", "mobiles"),
    "20:A2:E4": ("Apple", "mobiles"),
    "20:C9:D0": ("Apple", "mobiles"),
    "24:24:0E": ("Apple", "mobiles"),
    "24:A0:74": ("Apple", "mobiles"),
    "24:AB:81": ("Apple", "mobiles"),
    "24:F0:94": ("Apple", "mobiles"),
    "28:6A:BA": ("Apple", "mobiles"),
    "28:A0:2B": ("Apple", "mobiles"),
    "28:CF:DA": ("Apple", "mobiles"),
    "28:CF:E9": ("Apple", "mobiles"),
    "28:E0:2C": ("Apple", "mobiles"),
    "28:E1:4C": ("Apple", "mobiles"),
    "28:F0:76": ("Apple", "mobiles"),
    "2C:B4:3A": ("Apple", "mobiles"),
    "2C:BE:08": ("Apple", "mobiles"),
    "2C:F0:EE": ("Apple", "mobiles"),
    "30:10:E4": ("Apple", "mobiles"),
    "30:35:AD": ("Apple", "mobiles"),
    "30:63:6B": ("Apple", "mobiles"),
    "30:90:AB": ("Apple", "mobiles"),
    "30:F7:C5": ("Apple", "mobiles"),

    # Samsung - phones, TVs, appliances
    "00:00:F0": ("Samsung", "mobiles"),
    "00:07:AB": ("Samsung", "mobiles"),
    "00:12:47": ("Samsung", "mobiles"),
    "00:12:FB": ("Samsung", "mobiles"),
    "00:13:77": ("Samsung", "mobiles"),
    "00:15:99": ("Samsung", "mobiles"),
    "00:16:32": ("Samsung", "mobiles"),
    "00:16:6B": ("Samsung", "mobiles"),
    "00:16:6C": ("Samsung", "mobiles"),
    "00:17:C9": ("Samsung", "mobiles"),
    "00:17:D5": ("Samsung", "mobiles"),
    "00:18:AF": ("Samsung", "mobiles"),
    "00:1A:8A": ("Samsung", "mobiles"),
    "00:1B:98": ("Samsung", "mobiles"),
    "00:1C:43": ("Samsung", "mobiles"),
    "00:1D:25": ("Samsung", "mobiles"),
    "00:1D:F6": ("Samsung", "mobiles"),
    "00:1E:7D": ("Samsung", "mobiles"),
    "00:1F:CC": ("Samsung", "mobiles"),
    "00:1F:CD": ("Samsung", "mobiles"),
    "00:21:19": ("Samsung", "mobiles"),
    "00:21:4C": ("Samsung", "mobiles"),
    "00:21:D1": ("Samsung", "tvs"),
    "00:21:D2": ("Samsung", "tvs"),
    "00:23:39": ("Samsung", "mobiles"),
    "00:23:3A": ("Samsung", "tvs"),
    "00:23:99": ("Samsung", "mobiles"),
    "00:23:D6": ("Samsung", "mobiles"),
    "00:23:D7": ("Samsung", "mobiles"),
    "00:24:54": ("Samsung", "mobiles"),
    "00:24:90": ("Samsung", "mobiles"),
    "00:24:91": ("Samsung", "tvs"),
    "00:25:66": ("Samsung", "mobiles"),
    "00:25:67": ("Samsung", "tvs"),
    "00:26:37": ("Samsung", "mobiles"),
    "00:E0:64": ("Samsung", "mobiles"),
    "08:08:C2": ("Samsung", "mobiles"),
    "08:37:3D": ("Samsung", "mobiles"),
    "08:D4:2B": ("Samsung", "mobiles"),
    "08:EC:A9": ("Samsung", "mobiles"),
    "08:FD:0E": ("Samsung", "mobiles"),
    "0C:14:20": ("Samsung", "mobiles"),
    "0C:71:5D": ("Samsung", "mobiles"),
    "10:1D:C0": ("Samsung", "mobiles"),
    "10:30:47": ("Samsung", "mobiles"),
    "14:49:E0": ("Samsung", "mobiles"),
    "14:89:FD": ("Samsung", "mobiles"),
    "18:22:7E": ("Samsung", "mobiles"),
    "18:3A:2D": ("Samsung", "mobiles"),
    "18:67:B0": ("Samsung", "mobiles"),
    "1C:62:B8": ("Samsung", "mobiles"),
    "1C:AF:05": ("Samsung", "mobiles"),
    "20:13:E0": ("Samsung", "mobiles"),
    "20:D3:90": ("Samsung", "mobiles"),
    "24:18:1D": ("Samsung", "mobiles"),
    "24:4B:03": ("Samsung", "mobiles"),
    "28:27:BF": ("Samsung", "mobiles"),
    "28:98:7B": ("Samsung", "mobiles"),
    "28:BA:B5": ("Samsung", "mobiles"),
    "2C:AE:2B": ("Samsung", "mobiles"),
    "30:CB:F8": ("Samsung", "mobiles"),
    "34:23:BA": ("Samsung", "tvs"),
    "34:C3:AC": ("Samsung", "mobiles"),
    "38:01:97": ("Samsung", "mobiles"),
    "38:0A:94": ("Samsung", "mobiles"),
    "38:16:D1": ("Samsung", "mobiles"),
    "3C:5A:37": ("Samsung", "mobiles"),
    "3C:62:00": ("Samsung", "mobiles"),
    "40:0E:85": ("Samsung", "mobiles"),
    "44:6D:6C": ("Samsung", "mobiles"),
    "44:78:3E": ("Samsung", "mobiles"),
    "48:44:F7": ("Samsung", "mobiles"),
    "4C:3C:16": ("Samsung", "mobiles"),
    "50:01:BB": ("Samsung", "mobiles"),
    "50:32:75": ("Samsung", "mobiles"),
    "50:A4:C8": ("Samsung", "mobiles"),
    "50:B7:C3": ("Samsung", "mobiles"),
    "50:F5:20": ("Samsung", "mobiles"),
    "54:92:BE": ("Samsung", "mobiles"),
    "54:FA:3E": ("Samsung", "mobiles"),
    "58:C3:8B": ("Samsung", "mobiles"),
    "5C:0A:5B": ("Samsung", "mobiles"),
    "5C:3C:27": ("Samsung", "mobiles"),
    "5C:E8:EB": ("Samsung", "mobiles"),
    "60:6B:BD": ("Samsung", "mobiles"),
    "60:A1:0A": ("Samsung", "mobiles"),
    "64:B3:10": ("Samsung", "mobiles"),
    "68:27:37": ("Samsung", "mobiles"),
    "6C:F3:73": ("Samsung", "mobiles"),
    "70:F9:27": ("Samsung", "mobiles"),
    "74:45:CE": ("Samsung", "mobiles"),
    "78:1F:DB": ("Samsung", "mobiles"),
    "78:25:AD": ("Samsung", "mobiles"),
    "78:40:E4": ("Samsung", "mobiles"),
    "78:47:1D": ("Samsung", "mobiles"),
    "78:52:1A": ("Samsung", "mobiles"),
    "7C:0A:3F": ("Samsung", "mobiles"),
    "7C:61:66": ("Samsung", "mobiles"),
    "80:18:A7": ("Samsung", "mobiles"),
    "80:65:6D": ("Samsung", "mobiles"),
    "84:11:9E": ("Samsung", "mobiles"),
    "84:25:DB": ("Samsung", "mobiles"),
    "84:2E:27": ("Samsung", "mobiles"),
    "84:38:35": ("Samsung", "mobiles"),
    "84:55:A5": ("Samsung", "mobiles"),
    "84:98:66": ("Samsung", "mobiles"),
    "84:B5:41": ("Samsung", "mobiles"),
    "88:32:9B": ("Samsung", "mobiles"),
    "88:AD:D2": ("Samsung", "mobiles"),
    "8C:77:12": ("Samsung", "mobiles"),
    "8C:F5:A3": ("Samsung", "mobiles"),
    "90:18:7C": ("Samsung", "mobiles"),
    "90:F1:AA": ("Samsung", "mobiles"),
    "94:01:C2": ("Samsung", "mobiles"),
    "94:35:0A": ("Samsung", "mobiles"),
    "94:51:03": ("Samsung", "mobiles"),
    "94:63:D1": ("Samsung", "mobiles"),
    "94:B1:0A": ("Samsung", "mobiles"),
    "98:0C:82": ("Samsung", "mobiles"),
    "98:52:B1": ("Samsung", "mobiles"),
    "9C:02:98": ("Samsung", "mobiles"),
    "9C:3A:AF": ("Samsung", "mobiles"),
    "A0:07:98": ("Samsung", "mobiles"),
    "A0:0B:BA": ("Samsung", "mobiles"),
    "A0:82:1F": ("Samsung", "mobiles"),
    "A4:07:B6": ("Samsung", "mobiles"),
    "A4:D1:8C": ("Samsung", "mobiles"),
    "A8:06:00": ("Samsung", "mobiles"),
    "A8:41:F4": ("Samsung", "mobiles"),
    "AC:36:13": ("Samsung", "mobiles"),
    "AC:5F:3E": ("Samsung", "mobiles"),
    "B0:47:BF": ("Samsung", "mobiles"),
    "B0:72:BF": ("Samsung", "mobiles"),
    "B4:3A:28": ("Samsung", "mobiles"),
    "B4:79:A7": ("Samsung", "mobiles"),
    "B4:CE:F6": ("Samsung", "mobiles"),
    "B8:27:EB": ("Samsung", "mobiles"),
    "B8:5A:73": ("Samsung", "mobiles"),
    "B8:D7:AF": ("Samsung", "mobiles"),
    "BC:20:A4": ("Samsung", "mobiles"),
    "BC:72:B1": ("Samsung", "mobiles"),
    "BC:76:70": ("Samsung", "mobiles"),
    "BC:85:1F": ("Samsung", "mobiles"),
    "C0:BD:D1": ("Samsung", "mobiles"),
    "C4:42:02": ("Samsung", "mobiles"),
    "C4:50:06": ("Samsung", "mobiles"),
    "C4:57:6E": ("Samsung", "mobiles"),
    "C4:73:1E": ("Samsung", "mobiles"),
    "C8:19:F7": ("Samsung", "mobiles"),
    "C8:BA:94": ("Samsung", "mobiles"),
    "CC:07:AB": ("Samsung", "mobiles"),
    "D0:22:BE": ("Samsung", "mobiles"),
    "D0:25:98": ("Samsung", "mobiles"),
    "D0:59:E4": ("Samsung", "mobiles"),
    "D0:66:7B": ("Samsung", "mobiles"),
    "D0:87:E2": ("Samsung", "mobiles"),
    "D4:88:90": ("Samsung", "mobiles"),
    "D8:57:EF": ("Samsung", "mobiles"),
    "D8:90:E8": ("Samsung", "mobiles"),
    "D8:C4:E9": ("Samsung", "mobiles"),
    "DC:71:96": ("Samsung", "mobiles"),
    "E0:CB:1D": ("Samsung", "mobiles"),
    "E0:DB:10": ("Samsung", "mobiles"),
    "E4:12:1D": ("Samsung", "mobiles"),
    "E4:58:B8": ("Samsung", "mobiles"),
    "E4:7C:F9": ("Samsung", "mobiles"),
    "E4:92:FB": ("Samsung", "mobiles"),
    "E8:03:9A": ("Samsung", "mobiles"),
    "E8:50:8B": ("Samsung", "mobiles"),
    "EC:1F:72": ("Samsung", "mobiles"),
    "EC:9B:F3": ("Samsung", "mobiles"),
    "F0:25:B7": ("Samsung", "mobiles"),
    "F0:5A:09": ("Samsung", "mobiles"),
    "F0:6B:CA": ("Samsung", "mobiles"),
    "F0:72:8C": ("Samsung", "mobiles"),
    "F4:09:D8": ("Samsung", "mobiles"),
    "F4:42:8F": ("Samsung", "mobiles"),
    "F4:7B:5E": ("Samsung", "mobiles"),
    "F8:04:2E": ("Samsung", "mobiles"),
    "FC:A1:3E": ("Samsung", "mobiles"),
    "FC:F1:36": ("Samsung", "mobiles"),

    # Google / Android devices
    "00:1A:11": ("Google", "mobiles"),
    "08:9E:08": ("Google", "multimedia"),
    "18:D6:C7": ("Google", "multimedia"),
    "30:FD:38": ("Google", "multimedia"),
    "3C:5A:B4": ("Google", "multimedia"),
    "48:D6:D5": ("Google", "multimedia"),
    "54:60:09": ("Google", "multimedia"),
    "58:CB:52": ("Google", "multimedia"),
    "6C:AD:F8": ("Google", "multimedia"),
    "7C:2E:BD": ("Google", "multimedia"),
    "94:EB:2C": ("Google", "multimedia"),
    "A4:77:33": ("Google", "multimedia"),
    "D4:F5:47": ("Google", "multimedia"),
    "F4:F5:D8": ("Google", "multimedia"),
    "F4:F5:E8": ("Google", "multimedia"),

    # Roku
    "00:0D:4B": ("Roku", "multimedia"),
    "08:05:81": ("Roku", "multimedia"),
    "10:59:32": ("Roku", "multimedia"),
    "20:EF:BD": ("Roku", "multimedia"),
    "AC:3A:7A": ("Roku", "multimedia"),
    "B0:A7:37": ("Roku", "multimedia"),
    "B8:3E:59": ("Roku", "multimedia"),
    "BC:D7:D4": ("Roku", "multimedia"),
    "C8:3A:6B": ("Roku", "multimedia"),
    "D0:4D:C6": ("Roku", "multimedia"),
    "D8:31:34": ("Roku", "multimedia"),
    "DC:3A:5E": ("Roku", "multimedia"),

    # Amazon (Echo, Fire, Ring)
    "00:FC:8B": ("Amazon", "iot"),
    "0C:47:C9": ("Amazon", "iot"),
    "10:CE:A9": ("Amazon", "iot"),
    "14:91:82": ("Amazon", "iot"),
    "18:74:2E": ("Amazon", "iot"),
    "1C:12:B0": ("Amazon", "iot"),
    "24:4C:E3": ("Amazon", "iot"),
    "28:C2:1F": ("Amazon", "iot"),
    "34:D2:70": ("Amazon", "iot"),
    "38:F7:3D": ("Amazon", "iot"),
    "3C:5C:C4": ("Amazon", "iot"),
    "40:A2:DB": ("Amazon", "iot"),
    "44:00:49": ("Amazon", "iot"),
    "44:65:0D": ("Amazon", "multimedia"),
    "48:A9:D2": ("Amazon", "iot"),
    "4C:EF:C0": ("Amazon", "iot"),
    "50:DC:E7": ("Amazon", "iot"),
    "5C:41:5A": ("Amazon", "iot"),
    "68:37:E9": ("Amazon", "iot"),
    "68:54:FD": ("Amazon", "iot"),
    "6C:56:97": ("Amazon", "iot"),
    "74:75:48": ("Amazon", "iot"),
    "74:C2:46": ("Amazon", "iot"),
    "78:E1:03": ("Amazon", "iot"),
    "84:D6:D0": ("Amazon", "iot"),
    "8C:AE:4C": ("Amazon", "iot"),
    "94:9F:3E": ("Amazon", "iot"),
    "A0:02:DC": ("Amazon", "iot"),
    "A4:08:EA": ("Amazon", "iot"),
    "AC:63:BE": ("Amazon", "iot"),
    "B0:FC:36": ("Amazon", "iot"),
    "B4:7C:9C": ("Amazon", "iot"),
    "CC:F7:35": ("Amazon", "iot"),
    "F0:27:2D": ("Amazon", "iot"),
    "F0:F0:A4": ("Amazon", "iot"),
    "FC:65:DE": ("Amazon", "iot"),
    "FE:B4:62": ("Amazon", "iot"),

    # Microsoft / Xbox
    "00:0D:3A": ("Microsoft", "desktops"),
    "00:12:5A": ("Microsoft", "desktops"),
    "00:15:5D": ("Microsoft", "desktops"),
    "00:17:FA": ("Microsoft", "desktops"),
    "00:1D:D8": ("Microsoft", "gaming_consoles"),
    "00:22:48": ("Microsoft", "desktops"),
    "00:25:AE": ("Microsoft", "desktops"),
    "00:50:F2": ("Microsoft", "desktops"),
    "28:18:78": ("Microsoft", "desktops"),
    "30:59:B7": ("Microsoft", "desktops"),
    "58:82:A8": ("Microsoft", "gaming_consoles"),
    "60:45:BD": ("Microsoft", "desktops"),
    "7C:1E:52": ("Microsoft", "desktops"),
    "7C:ED:8D": ("Microsoft", "desktops"),
    "98:5F:D3": ("Microsoft", "desktops"),
    "B4:0E:DE": ("Microsoft", "desktops"),
    "C8:3F:26": ("Microsoft", "desktops"),
    "DC:B4:C4": ("Microsoft", "desktops"),

    # Sony PlayStation
    "00:04:1F": ("Sony", "gaming_consoles"),
    "00:13:15": ("Sony", "gaming_consoles"),
    "00:15:C1": ("Sony", "gaming_consoles"),
    "00:19:C5": ("Sony", "gaming_consoles"),
    "00:1D:0D": ("Sony", "gaming_consoles"),
    "00:1F:A7": ("Sony", "gaming_consoles"),
    "00:24:8D": ("Sony", "gaming_consoles"),
    "00:D9:D1": ("Sony", "gaming_consoles"),
    "04:98:F3": ("Sony", "gaming_consoles"),
    "28:0D:FC": ("Sony", "gaming_consoles"),
    "2C:CC:44": ("Sony", "gaming_consoles"),
    "70:9E:29": ("Sony", "gaming_consoles"),
    "78:C8:81": ("Sony", "gaming_consoles"),
    "A8:E3:EE": ("Sony", "gaming_consoles"),
    "BC:60:A7": ("Sony", "gaming_consoles"),
    "FC:0F:E6": ("Sony", "gaming_consoles"),

    # Nintendo
    "00:09:BF": ("Nintendo", "gaming_consoles"),
    "00:16:56": ("Nintendo", "gaming_consoles"),
    "00:17:AB": ("Nintendo", "gaming_consoles"),
    "00:19:1D": ("Nintendo", "gaming_consoles"),
    "00:1A:E9": ("Nintendo", "gaming_consoles"),
    "00:1B:7A": ("Nintendo", "gaming_consoles"),
    "00:1C:BE": ("Nintendo", "gaming_consoles"),
    "00:1D:BC": ("Nintendo", "gaming_consoles"),
    "00:1E:35": ("Nintendo", "gaming_consoles"),
    "00:1F:32": ("Nintendo", "gaming_consoles"),
    "00:1F:C5": ("Nintendo", "gaming_consoles"),
    "00:22:AA": ("Nintendo", "gaming_consoles"),
    "00:22:D7": ("Nintendo", "gaming_consoles"),
    "00:23:31": ("Nintendo", "gaming_consoles"),
    "00:23:CC": ("Nintendo", "gaming_consoles"),
    "00:24:44": ("Nintendo", "gaming_consoles"),
    "00:24:F3": ("Nintendo", "gaming_consoles"),
    "00:25:A0": ("Nintendo", "gaming_consoles"),
    "00:27:09": ("Nintendo", "gaming_consoles"),
    "2C:10:C1": ("Nintendo", "gaming_consoles"),
    "34:AF:2C": ("Nintendo", "gaming_consoles"),
    "40:D2:8A": ("Nintendo", "gaming_consoles"),
    "58:BD:A3": ("Nintendo", "gaming_consoles"),
    "7C:BB:8A": ("Nintendo", "gaming_consoles"),
    "8C:CD:E8": ("Nintendo", "gaming_consoles"),
    "98:41:5C": ("Nintendo", "gaming_consoles"),
    "98:B6:E9": ("Nintendo", "gaming_consoles"),
    "A4:38:CC": ("Nintendo", "gaming_consoles"),
    "A4:C0:E1": ("Nintendo", "gaming_consoles"),
    "B8:AE:6E": ("Nintendo", "gaming_consoles"),
    "CC:FB:65": ("Nintendo", "gaming_consoles"),
    "D8:6B:F7": ("Nintendo", "gaming_consoles"),
    "E0:0C:7F": ("Nintendo", "gaming_consoles"),
    "E8:4E:CE": ("Nintendo", "gaming_consoles"),

    # HP Printers
    "00:00:63": ("HP", "printers"),
    "00:01:E6": ("HP", "printers"),
    "00:02:A5": ("HP", "printers"),
    "00:08:02": ("HP", "printers"),
    "00:0B:CD": ("HP", "printers"),
    "00:0D:9D": ("HP", "printers"),
    "00:0E:7F": ("HP", "printers"),
    "00:11:0A": ("HP", "printers"),
    "00:11:85": ("HP", "printers"),
    "00:12:79": ("HP", "printers"),
    "00:13:21": ("HP", "printers"),
    "00:14:38": ("HP", "printers"),
    "00:14:C2": ("HP", "printers"),
    "00:15:60": ("HP", "printers"),
    "00:16:35": ("HP", "printers"),
    "00:17:08": ("HP", "printers"),
    "00:17:A4": ("HP", "printers"),
    "00:18:FE": ("HP", "printers"),
    "00:19:BB": ("HP", "printers"),
    "00:1A:4B": ("HP", "printers"),
    "00:1B:78": ("HP", "printers"),
    "00:1C:C4": ("HP", "printers"),
    "00:1E:0B": ("HP", "printers"),
    "00:1F:29": ("HP", "printers"),
    "00:21:5A": ("HP", "printers"),
    "00:22:64": ("HP", "printers"),
    "00:23:7D": ("HP", "printers"),
    "00:24:81": ("HP", "printers"),
    "00:25:B3": ("HP", "printers"),
    "00:26:55": ("HP", "printers"),
    "00:30:6E": ("HP", "printers"),
    "00:30:C1": ("HP", "printers"),
    "00:40:17": ("HP", "printers"),
    "00:80:A0": ("HP", "printers"),
    "08:2E:5F": ("HP", "printers"),
    "10:1F:74": ("HP", "printers"),
    "10:60:4B": ("HP", "printers"),
    "18:A9:05": ("HP", "printers"),
    "1C:C1:DE": ("HP", "printers"),
    "28:92:4A": ("HP", "printers"),
    "2C:41:38": ("HP", "printers"),
    "2C:44:FD": ("HP", "printers"),
    "2C:59:E5": ("HP", "printers"),
    "3C:D9:2B": ("HP", "printers"),
    "40:B0:34": ("HP", "printers"),
    "48:0F:CF": ("HP", "printers"),
    "64:51:06": ("HP", "printers"),
    "68:B5:99": ("HP", "printers"),
    "78:AC:C0": ("HP", "printers"),
    "80:CE:62": ("HP", "printers"),
    "94:57:A5": ("HP", "printers"),
    "98:E7:F4": ("HP", "printers"),
    "A0:D3:C1": ("HP", "printers"),
    "A4:5D:36": ("HP", "printers"),
    "B0:5A:DA": ("HP", "printers"),
    "B4:B5:2F": ("HP", "printers"),
    "C4:34:6B": ("HP", "printers"),
    "C8:D3:FF": ("HP", "printers"),
    "D4:C9:EF": ("HP", "printers"),
    "E4:E7:49": ("HP", "printers"),
    "EC:B1:D7": ("HP", "printers"),

    # Canon Printers
    "00:00:85": ("Canon", "printers"),
    "00:1E:8F": ("Canon", "printers"),
    "18:0C:AC": ("Canon", "printers"),
    "3C:15:FB": ("Canon", "printers"),
    "84:BA:3B": ("Canon", "printers"),
    "C4:AC:59": ("Canon", "printers"),
    "F4:81:39": ("Canon", "printers"),

    # Epson Printers
    "00:00:48": ("Epson", "printers"),
    "00:26:AB": ("Epson", "printers"),
    "44:D2:44": ("Epson", "printers"),
    "64:EB:8C": ("Epson", "printers"),
    "A4:EE:57": ("Epson", "printers"),
    "AC:18:26": ("Epson", "printers"),
    "C8:2E:18": ("Epson", "printers"),

    # Nest / Google Home
    "18:B4:30": ("Nest", "iot"),
    "64:16:66": ("Nest", "iot"),

    # Ring (Amazon)
    "34:3E:A4": ("Ring", "cameras"),
    "4C:57:CA": ("Ring", "cameras"),
    "5C:47:5E": ("Ring", "cameras"),
    "B0:09:DA": ("Ring", "cameras"),

    # Hikvision (cameras)
    "28:57:BE": ("Hikvision", "cameras"),
    "44:19:B6": ("Hikvision", "cameras"),
    "54:C4:15": ("Hikvision", "cameras"),
    "A4:14:37": ("Hikvision", "cameras"),
    "C0:56:E3": ("Hikvision", "cameras"),
    "C4:2F:90": ("Hikvision", "cameras"),

    # Dahua (cameras)
    "3C:EF:8C": ("Dahua", "cameras"),
    "E0:50:8B": ("Dahua", "cameras"),

    # TP-Link (network)
    "14:CC:20": ("TP-Link", "network"),
    "14:EB:B6": ("TP-Link", "iot"),
    "18:A6:F7": ("TP-Link", "network"),
    "1C:3B:F3": ("TP-Link", "network"),
    "30:DE:4B": ("TP-Link", "network"),
    "50:C7:BF": ("TP-Link", "network"),
    "54:AF:97": ("TP-Link", "network"),
    "5C:A6:E6": ("TP-Link", "network"),
    "60:32:B1": ("TP-Link", "network"),
    "64:6E:97": ("TP-Link", "network"),
    "78:8C:B5": ("TP-Link", "network"),
    "90:F6:52": ("TP-Link", "network"),
    "98:DA:C4": ("TP-Link", "network"),
    "A4:2B:B0": ("TP-Link", "network"),
    "B0:4E:26": ("TP-Link", "network"),
    "B0:95:75": ("TP-Link", "network"),
    "C0:06:C3": ("TP-Link", "iot"),
    "C0:25:E9": ("TP-Link", "network"),
    "CC:32:E5": ("TP-Link", "network"),
    "D4:6E:0E": ("TP-Link", "network"),
    "D8:07:B6": ("TP-Link", "network"),
    "EC:08:6B": ("TP-Link", "network"),
    "EC:17:2F": ("TP-Link", "network"),
    "F4:EC:38": ("TP-Link", "network"),
    "F8:D1:11": ("TP-Link", "network"),

    # Netgear (network)
    "00:09:5B": ("Netgear", "network"),
    "00:0F:B5": ("Netgear", "network"),
    "00:14:6C": ("Netgear", "network"),
    "00:18:4D": ("Netgear", "network"),
    "00:1B:2F": ("Netgear", "network"),
    "00:1E:2A": ("Netgear", "network"),
    "00:1F:33": ("Netgear", "network"),
    "00:22:3F": ("Netgear", "network"),
    "00:24:B2": ("Netgear", "network"),
    "00:26:F2": ("Netgear", "network"),
    "04:A1:51": ("Netgear", "network"),
    "08:BD:43": ("Netgear", "network"),
    "10:0C:6B": ("Netgear", "network"),
    "10:DA:43": ("Netgear", "network"),
    "20:0C:C8": ("Netgear", "network"),
    "20:E5:2A": ("Netgear", "network"),
    "28:C6:8E": ("Netgear", "network"),
    "2C:B0:5D": ("Netgear", "network"),
    "30:46:9A": ("Netgear", "network"),
    "30:B5:C2": ("Netgear", "network"),
    "3C:37:86": ("Netgear", "network"),
    "44:94:FC": ("Netgear", "network"),
    "4C:60:DE": ("Netgear", "network"),
    "6C:B0:CE": ("Netgear", "network"),
    "84:1B:5E": ("Netgear", "network"),
    "8C:3B:AD": ("Netgear", "network"),
    "9C:3D:CF": ("Netgear", "network"),
    "A0:04:60": ("Netgear", "network"),
    "A0:21:B7": ("Netgear", "network"),
    "A0:40:A0": ("Netgear", "network"),
    "A4:2B:8C": ("Netgear", "network"),
    "B0:39:56": ("Netgear", "network"),
    "B0:7F:B9": ("Netgear", "network"),
    "C0:3F:0E": ("Netgear", "network"),
    "C0:FF:D4": ("Netgear", "network"),
    "C4:04:15": ("Netgear", "network"),
    "C4:3D:C7": ("Netgear", "network"),
    "CC:40:D0": ("Netgear", "network"),
    "DC:EF:09": ("Netgear", "network"),
    "E0:46:9A": ("Netgear", "network"),
    "E0:91:F5": ("Netgear", "network"),
    "E4:F4:C6": ("Netgear", "network"),
    "F8:73:94": ("Netgear", "network"),

    # Ubiquiti (network)
    "00:15:6D": ("Ubiquiti", "network"),
    "00:27:22": ("Ubiquiti", "network"),
    "04:18:D6": ("Ubiquiti", "network"),
    "18:E8:29": ("Ubiquiti", "network"),
    "24:5A:4C": ("Ubiquiti", "network"),
    "24:A4:3C": ("Ubiquiti", "network"),
    "44:D9:E7": ("Ubiquiti", "network"),
    "68:72:51": ("Ubiquiti", "network"),
    "78:8A:20": ("Ubiquiti", "network"),
    "80:2A:A8": ("Ubiquiti", "network"),
    "AC:8B:A9": ("Ubiquiti", "network"),
    "B4:FB:E4": ("Ubiquiti", "network"),
    "D0:21:F9": ("Ubiquiti", "network"),
    "DC:9F:DB": ("Ubiquiti", "network"),
    "E0:63:DA": ("Ubiquiti", "network"),
    "F0:9F:C2": ("Ubiquiti", "network"),
    "FC:EC:DA": ("Ubiquiti", "network"),

    # LG (TVs, appliances)
    "00:1C:62": ("LG", "tvs"),
    "00:1E:75": ("LG", "tvs"),
    "00:1F:6B": ("LG", "tvs"),
    "00:1F:E3": ("LG", "tvs"),
    "00:22:A9": ("LG", "tvs"),
    "00:26:E2": ("LG", "tvs"),
    "00:34:DA": ("LG", "tvs"),
    "00:AA:70": ("LG", "tvs"),
    "00:E0:91": ("LG", "tvs"),
    "08:D4:6A": ("LG", "tvs"),
    "10:68:3F": ("LG", "tvs"),
    "14:C9:13": ("LG", "tvs"),
    "20:3D:BD": ("LG", "tvs"),
    "28:CF:E9": ("LG", "tvs"),
    "2C:54:CF": ("LG", "tvs"),
    "30:19:66": ("LG", "tvs"),
    "34:4D:F7": ("LG", "tvs"),
    "38:8C:50": ("LG", "tvs"),
    "3C:BD:D8": ("LG", "tvs"),
    "40:B0:FA": ("LG", "tvs"),
    "58:A2:B5": ("LG", "tvs"),
    "5C:6A:80": ("LG", "tvs"),
    "64:99:5D": ("LG", "tvs"),
    "6C:E8:73": ("LG", "tvs"),
    "74:40:BB": ("LG", "tvs"),
    "78:F8:82": ("LG", "tvs"),
    "88:07:4B": ("LG", "tvs"),
    "88:C9:D0": ("LG", "tvs"),
    "8C:3A:E3": ("LG", "tvs"),
    "A0:39:F7": ("LG", "tvs"),
    "A8:16:B2": ("LG", "tvs"),
    "A8:23:FE": ("LG", "tvs"),
    "AC:0D:1B": ("LG", "tvs"),
    "BC:F5:AC": ("LG", "tvs"),
    "C4:36:6C": ("LG", "tvs"),
    "C4:9A:02": ("LG", "tvs"),
    "CC:2D:83": ("LG", "tvs"),
    "CC:FA:00": ("LG", "tvs"),
    "D0:D0:03": ("LG", "tvs"),
    "E8:F2:E2": ("LG", "tvs"),
    "F8:0C:F3": ("LG", "tvs"),
    "FC:75:16": ("LG", "tvs"),

    # Sonos (multimedia)
    "00:0E:58": ("Sonos", "multimedia"),
    "34:7E:5C": ("Sonos", "multimedia"),
    "48:A6:B8": ("Sonos", "multimedia"),
    "5C:AA:FD": ("Sonos", "multimedia"),
    "78:28:CA": ("Sonos", "multimedia"),
    "94:9F:3E": ("Sonos", "multimedia"),
    "B8:E9:37": ("Sonos", "multimedia"),

    # Xiaomi (mobiles, IoT)
    "00:9E:C8": ("Xiaomi", "mobiles"),
    "04:CF:8C": ("Xiaomi", "iot"),
    "0C:1D:AF": ("Xiaomi", "mobiles"),
    "10:2A:B3": ("Xiaomi", "iot"),
    "14:F6:5A": ("Xiaomi", "mobiles"),
    "18:59:36": ("Xiaomi", "mobiles"),
    "1C:5A:3E": ("Xiaomi", "iot"),
    "20:47:DA": ("Xiaomi", "iot"),
    "28:6C:07": ("Xiaomi", "mobiles"),
    "28:E3:1F": ("Xiaomi", "mobiles"),
    "2C:D0:5A": ("Xiaomi", "iot"),
    "34:80:B3": ("Xiaomi", "mobiles"),
    "34:CE:00": ("Xiaomi", "iot"),
    "38:A4:ED": ("Xiaomi", "mobiles"),
    "3C:BD:3E": ("Xiaomi", "iot"),
    "40:31:3C": ("Xiaomi", "iot"),
    "44:23:7C": ("Xiaomi", "iot"),
    "48:A4:72": ("Xiaomi", "mobiles"),
    "4C:49:E3": ("Xiaomi", "iot"),
    "50:64:2B": ("Xiaomi", "iot"),
    "50:EC:50": ("Xiaomi", "mobiles"),
    "54:48:E6": ("Xiaomi", "mobiles"),
    "58:44:98": ("Xiaomi", "iot"),
    "5C:50:15": ("Xiaomi", "mobiles"),
    "60:AB:67": ("Xiaomi", "mobiles"),
    "64:09:80": ("Xiaomi", "iot"),
    "64:CC:2E": ("Xiaomi", "mobiles"),
    "68:AB:1E": ("Xiaomi", "iot"),
    "6C:5A:B0": ("Xiaomi", "iot"),
    "74:23:44": ("Xiaomi", "iot"),
    "74:51:BA": ("Xiaomi", "iot"),
    "78:02:F8": ("Xiaomi", "iot"),
    "78:11:DC": ("Xiaomi", "iot"),
    "7C:49:EB": ("Xiaomi", "iot"),
    "84:F3:EB": ("Xiaomi", "iot"),
    "8C:DE:F9": ("Xiaomi", "iot"),
    "98:FA:E3": ("Xiaomi", "iot"),
    "9C:99:A0": ("Xiaomi", "mobiles"),
    "A4:77:F3": ("Xiaomi", "mobiles"),
    "AC:C1:EE": ("Xiaomi", "iot"),
    "B0:E2:35": ("Xiaomi", "iot"),
    "C4:0B:CB": ("Xiaomi", "iot"),
    "C8:02:8F": ("Xiaomi", "iot"),
    "D4:3B:04": ("Xiaomi", "iot"),
    "D8:E0:E1": ("Xiaomi", "iot"),
    "E4:AA:EC": ("Xiaomi", "iot"),
    "F0:B4:29": ("Xiaomi", "iot"),
    "F4:02:70": ("Xiaomi", "mobiles"),
    "F8:A4:5F": ("Xiaomi", "iot"),
    "FC:64:BA": ("Xiaomi", "iot"),

    # Intel (desktops/laptops)
    "00:02:B3": ("Intel", "desktops"),
    "00:03:47": ("Intel", "desktops"),
    "00:04:23": ("Intel", "desktops"),
    "00:07:E9": ("Intel", "desktops"),
    "00:0C:F1": ("Intel", "desktops"),
    "00:0E:0C": ("Intel", "desktops"),
    "00:0E:35": ("Intel", "desktops"),
    "00:11:11": ("Intel", "desktops"),
    "00:12:F0": ("Intel", "desktops"),
    "00:13:02": ("Intel", "desktops"),
    "00:13:20": ("Intel", "desktops"),
    "00:13:CE": ("Intel", "desktops"),
    "00:13:E8": ("Intel", "desktops"),
    "00:15:00": ("Intel", "desktops"),
    "00:15:17": ("Intel", "desktops"),
    "00:16:6F": ("Intel", "desktops"),
    "00:16:76": ("Intel", "desktops"),
    "00:16:EA": ("Intel", "desktops"),
    "00:16:EB": ("Intel", "desktops"),
    "00:18:DE": ("Intel", "desktops"),
    "00:19:D1": ("Intel", "desktops"),
    "00:19:D2": ("Intel", "desktops"),
    "00:1B:21": ("Intel", "desktops"),
    "00:1B:77": ("Intel", "desktops"),
    "00:1C:BF": ("Intel", "desktops"),
    "00:1C:C0": ("Intel", "desktops"),
    "00:1D:E0": ("Intel", "desktops"),
    "00:1D:E1": ("Intel", "desktops"),
    "00:1E:64": ("Intel", "desktops"),
    "00:1E:65": ("Intel", "desktops"),
    "00:1F:3B": ("Intel", "desktops"),
    "00:1F:3C": ("Intel", "desktops"),
    "00:21:5C": ("Intel", "desktops"),
    "00:21:5D": ("Intel", "desktops"),
    "00:21:6A": ("Intel", "desktops"),
    "00:21:6B": ("Intel", "desktops"),
    "00:22:FA": ("Intel", "desktops"),
    "00:22:FB": ("Intel", "desktops"),
    "00:23:14": ("Intel", "desktops"),
    "00:23:15": ("Intel", "desktops"),
    "00:24:D6": ("Intel", "desktops"),
    "00:24:D7": ("Intel", "desktops"),
    "00:26:C6": ("Intel", "desktops"),
    "00:26:C7": ("Intel", "desktops"),
    "00:27:10": ("Intel", "desktops"),
    "24:77:03": ("Intel", "desktops"),
    "34:13:E8": ("Intel", "desktops"),
    "34:E6:AD": ("Intel", "desktops"),
    "3C:97:0E": ("Intel", "desktops"),
    "48:51:B7": ("Intel", "desktops"),
    "4C:34:88": ("Intel", "desktops"),
    "58:91:CF": ("Intel", "desktops"),
    "58:94:6B": ("Intel", "desktops"),
    "5C:51:4F": ("Intel", "desktops"),
    "5C:C5:D4": ("Intel", "desktops"),
    "60:57:18": ("Intel", "desktops"),
    "60:6C:66": ("Intel", "desktops"),
    "64:5A:04": ("Intel", "desktops"),
    "68:05:CA": ("Intel", "desktops"),
    "6C:29:95": ("Intel", "desktops"),
    "70:1C:E7": ("Intel", "desktops"),
    "78:0C:B8": ("Intel", "desktops"),
    "78:92:9C": ("Intel", "desktops"),
    "7C:5C:F8": ("Intel", "desktops"),
    "80:86:F2": ("Intel", "desktops"),
    "80:CE:62": ("Intel", "desktops"),
    "84:3A:4B": ("Intel", "desktops"),
    "84:A6:C8": ("Intel", "desktops"),
    "88:78:73": ("Intel", "desktops"),
    "8C:55:4A": ("Intel", "desktops"),
    "90:2E:16": ("Intel", "desktops"),
    "94:65:9C": ("Intel", "desktops"),
    "98:54:1B": ("Intel", "desktops"),
    "9C:DA:3E": ("Intel", "desktops"),
    "A0:36:9F": ("Intel", "desktops"),
    "A4:34:D9": ("Intel", "desktops"),
    "A4:4E:31": ("Intel", "desktops"),
    "AC:7B:A1": ("Intel", "desktops"),
    "B4:96:91": ("Intel", "desktops"),
    "B8:08:CF": ("Intel", "desktops"),
    "BC:77:37": ("Intel", "desktops"),
    "C0:B6:F9": ("Intel", "desktops"),
    "C4:8E:8F": ("Intel", "desktops"),
    "C8:5B:76": ("Intel", "desktops"),
    "CC:2F:71": ("Intel", "desktops"),
    "D0:7E:35": ("Intel", "desktops"),
    "D4:3D:7E": ("Intel", "desktops"),
    "DC:1B:A1": ("Intel", "desktops"),
    "E0:94:67": ("Intel", "desktops"),
    "E4:B3:18": ("Intel", "desktops"),
    "F4:06:69": ("Intel", "desktops"),
    "F8:63:3F": ("Intel", "desktops"),
    "FC:F8:AE": ("Intel", "desktops"),

    # Raspberry Pi
    "B8:27:EB": ("Raspberry Pi", "iot"),
    "DC:A6:32": ("Raspberry Pi", "iot"),
    "E4:5F:01": ("Raspberry Pi", "iot"),

    # Wyze (cameras/IoT)
    "2C:AA:8E": ("Wyze", "cameras"),
    "7C:78:B2": ("Wyze", "cameras"),
    "A4:DA:22": ("Wyze", "cameras"),

    # Philips Hue (IoT)
    "00:17:88": ("Philips Hue", "iot"),
    "EC:B5:FA": ("Philips Hue", "iot"),

    # Tesla (vehicles)
    "04:65:65": ("Tesla", "vehicles"),
    "4C:FC:AA": ("Tesla", "vehicles"),

    # Cisco (network)
    "00:00:0C": ("Cisco", "network"),
    "00:01:42": ("Cisco", "network"),
    "00:01:43": ("Cisco", "network"),
    "00:01:63": ("Cisco", "network"),
    "00:01:64": ("Cisco", "network"),
    "00:01:96": ("Cisco", "network"),
    "00:01:97": ("Cisco", "network"),
    "00:02:16": ("Cisco", "network"),
    "00:02:17": ("Cisco", "network"),
    "00:02:3D": ("Cisco", "network"),
    "00:02:4A": ("Cisco", "network"),
    "00:02:4B": ("Cisco", "network"),
    "00:02:7D": ("Cisco", "network"),
    "00:02:7E": ("Cisco", "network"),
    "00:02:B9": ("Cisco", "network"),
    "00:02:BA": ("Cisco", "network"),
    "00:02:FC": ("Cisco", "network"),
    "00:02:FD": ("Cisco", "network"),
    "00:03:31": ("Cisco", "network"),
    "00:03:32": ("Cisco", "network"),
    "00:03:6B": ("Cisco", "network"),
    "00:03:6C": ("Cisco", "network"),
    "00:03:9F": ("Cisco", "network"),
    "00:03:A0": ("Cisco", "network"),
    "00:03:E3": ("Cisco", "network"),
    "00:03:E4": ("Cisco", "network"),
    "00:03:FD": ("Cisco", "network"),
    "00:03:FE": ("Cisco", "network"),

    # Huawei (mobiles, network)
    "00:1E:10": ("Huawei", "mobiles"),
    "00:18:82": ("Huawei", "network"),
    "00:22:A1": ("Huawei", "mobiles"),
    "00:25:9E": ("Huawei", "mobiles"),
    "00:46:4B": ("Huawei", "mobiles"),
    "00:66:4B": ("Huawei", "mobiles"),
    "00:E0:FC": ("Huawei", "network"),
    "04:02:1F": ("Huawei", "mobiles"),
    "04:B0:E7": ("Huawei", "mobiles"),
    "04:C0:6F": ("Huawei", "mobiles"),
    "04:F9:38": ("Huawei", "mobiles"),
    "08:19:A6": ("Huawei", "mobiles"),
    "08:63:61": ("Huawei", "mobiles"),
    "0C:37:DC": ("Huawei", "mobiles"),
    "0C:45:BA": ("Huawei", "mobiles"),
    "10:1B:54": ("Huawei", "mobiles"),
    "10:44:00": ("Huawei", "network"),
    "10:47:80": ("Huawei", "mobiles"),
    "10:C6:1F": ("Huawei", "mobiles"),
    "14:30:04": ("Huawei", "mobiles"),
    "14:B9:68": ("Huawei", "mobiles"),
    "18:C5:8A": ("Huawei", "mobiles"),
    "1C:15:1F": ("Huawei", "mobiles"),
    "1C:8E:5C": ("Huawei", "mobiles"),
    "20:A6:80": ("Huawei", "mobiles"),
    "20:F3:A3": ("Huawei", "mobiles"),
    "24:09:95": ("Huawei", "mobiles"),
    "24:44:27": ("Huawei", "network"),
    "24:69:A5": ("Huawei", "mobiles"),
    "24:DB:AC": ("Huawei", "mobiles"),
    "28:31:52": ("Huawei", "mobiles"),
    "28:3C:E4": ("Huawei", "mobiles"),
    "28:6E:D4": ("Huawei", "mobiles"),
    "2C:AB:00": ("Huawei", "mobiles"),
    "30:D1:7E": ("Huawei", "mobiles"),
    "30:F3:35": ("Huawei", "mobiles"),
    "34:00:A3": ("Huawei", "network"),
    "34:12:98": ("Huawei", "mobiles"),
    "34:CD:BE": ("Huawei", "mobiles"),
    "38:37:8B": ("Huawei", "mobiles"),
    "38:F8:89": ("Huawei", "mobiles"),
    "3C:47:11": ("Huawei", "mobiles"),
    "3C:FA:43": ("Huawei", "mobiles"),
    "40:4D:8E": ("Huawei", "mobiles"),
    "40:CB:A8": ("Huawei", "mobiles"),
    "44:55:B1": ("Huawei", "mobiles"),
    "44:6A:2E": ("Huawei", "mobiles"),
    "44:C3:46": ("Huawei", "mobiles"),
    "48:00:31": ("Huawei", "mobiles"),
    "48:46:FB": ("Huawei", "mobiles"),
    "48:62:76": ("Huawei", "mobiles"),
    "48:A7:4E": ("Huawei", "mobiles"),
    "48:AD:08": ("Huawei", "network"),
    "48:DB:50": ("Huawei", "mobiles"),
    "4C:1F:CC": ("Huawei", "mobiles"),
    "4C:8B:EF": ("Huawei", "mobiles"),
    "4C:B1:6C": ("Huawei", "mobiles"),
    "50:01:6B": ("Huawei", "mobiles"),
    "50:A7:2B": ("Huawei", "mobiles"),
    "54:25:EA": ("Huawei", "mobiles"),
    "54:89:98": ("Huawei", "mobiles"),
    "54:A5:1B": ("Huawei", "mobiles"),
    "54:B1:21": ("Huawei", "mobiles"),
    "58:2A:F7": ("Huawei", "mobiles"),
    "5C:4C:A9": ("Huawei", "mobiles"),
    "5C:7D:5E": ("Huawei", "mobiles"),
    "5C:B3:95": ("Huawei", "mobiles"),
    "5C:F9:6A": ("Huawei", "mobiles"),
    "60:DE:44": ("Huawei", "mobiles"),
    "64:A6:51": ("Huawei", "mobiles"),
    "68:A0:F6": ("Huawei", "mobiles"),
    "6C:B7:49": ("Huawei", "mobiles"),
    "70:72:3C": ("Huawei", "mobiles"),
    "70:7B:E8": ("Huawei", "mobiles"),
    "70:8A:09": ("Huawei", "mobiles"),
    "70:A8:E3": ("Huawei", "mobiles"),
    "74:88:2A": ("Huawei", "mobiles"),
    "78:1D:BA": ("Huawei", "mobiles"),
    "78:6A:89": ("Huawei", "mobiles"),
    "7C:60:97": ("Huawei", "mobiles"),
    "7C:A1:77": ("Huawei", "mobiles"),
    "80:B6:55": ("Huawei", "mobiles"),
    "80:D0:9B": ("Huawei", "mobiles"),
    "84:A8:E4": ("Huawei", "mobiles"),
    "84:DB:AC": ("Huawei", "mobiles"),
    "88:28:B3": ("Huawei", "mobiles"),
    "88:53:D4": ("Huawei", "mobiles"),
    "88:CE:FA": ("Huawei", "network"),
    "8C:34:FD": ("Huawei", "mobiles"),
    "90:17:AC": ("Huawei", "mobiles"),
    "90:4E:2B": ("Huawei", "mobiles"),
    "90:67:1C": ("Huawei", "network"),
    "94:04:9C": ("Huawei", "mobiles"),
    "94:77:2B": ("Huawei", "mobiles"),
    "94:DB:C9": ("Huawei", "mobiles"),
    "98:9C:57": ("Huawei", "mobiles"),
    "9C:28:EF": ("Huawei", "mobiles"),
    "9C:74:1A": ("Huawei", "mobiles"),
    "9C:B2:B2": ("Huawei", "mobiles"),
    "A0:8C:F8": ("Huawei", "mobiles"),
    "A4:71:74": ("Huawei", "mobiles"),
    "A4:BA:76": ("Huawei", "mobiles"),
    "A4:DC:BE": ("Huawei", "mobiles"),
    "A8:CA:7B": ("Huawei", "mobiles"),
    "AC:61:EA": ("Huawei", "mobiles"),
    "AC:E2:15": ("Huawei", "mobiles"),
    "AC:E8:7B": ("Huawei", "mobiles"),
    "B0:5B:67": ("Huawei", "mobiles"),
    "B4:15:13": ("Huawei", "mobiles"),
    "B4:30:52": ("Huawei", "mobiles"),
    "B8:08:D7": ("Huawei", "mobiles"),
    "BC:25:E0": ("Huawei", "mobiles"),
    "BC:76:70": ("Huawei", "mobiles"),
    "C0:70:09": ("Huawei", "mobiles"),
    "C4:07:2F": ("Huawei", "mobiles"),
    "C4:86:E9": ("Huawei", "network"),
    "C8:14:79": ("Huawei", "mobiles"),
    "C8:D1:5E": ("Huawei", "mobiles"),
    "CC:A2:23": ("Huawei", "mobiles"),
    "CC:CC:81": ("Huawei", "mobiles"),
    "D0:7A:B5": ("Huawei", "mobiles"),
    "D4:6A:A8": ("Huawei", "mobiles"),
    "D4:6E:5C": ("Huawei", "mobiles"),
    "D4:B1:10": ("Huawei", "mobiles"),
    "D8:C7:71": ("Huawei", "mobiles"),
    "DC:D2:FC": ("Huawei", "mobiles"),
    "E0:19:1D": ("Huawei", "mobiles"),
    "E0:24:7F": ("Huawei", "mobiles"),
    "E0:97:96": ("Huawei", "mobiles"),
    "E4:0E:EE": ("Huawei", "mobiles"),
    "E4:68:A3": ("Huawei", "mobiles"),
    "E4:7E:66": ("Huawei", "mobiles"),
    "E8:08:8B": ("Huawei", "mobiles"),
    "E8:68:E7": ("Huawei", "network"),
    "E8:CD:2D": ("Huawei", "mobiles"),
    "EC:23:3D": ("Huawei", "mobiles"),
    "EC:CB:30": ("Huawei", "mobiles"),
    "F0:43:47": ("Huawei", "mobiles"),
    "F4:4C:7F": ("Huawei", "mobiles"),
    "F4:55:9C": ("Huawei", "mobiles"),
    "F4:63:1F": ("Huawei", "mobiles"),
    "F4:C7:14": ("Huawei", "mobiles"),
    "F4:E3:FB": ("Huawei", "mobiles"),
    "F8:01:13": ("Huawei", "mobiles"),
    "F8:3D:FF": ("Huawei", "mobiles"),
    "F8:4A:BF": ("Huawei", "mobiles"),
    "F8:E8:11": ("Huawei", "mobiles"),
    "FC:48:EF": ("Huawei", "mobiles"),

    # Dell (desktops/laptops)
    "00:06:5B": ("Dell", "desktops"),
    "00:08:74": ("Dell", "desktops"),
    "00:0B:DB": ("Dell", "desktops"),
    "00:0D:56": ("Dell", "desktops"),
    "00:0F:1F": ("Dell", "desktops"),
    "00:11:43": ("Dell", "desktops"),
    "00:12:3F": ("Dell", "desktops"),
    "00:13:72": ("Dell", "desktops"),
    "00:14:22": ("Dell", "desktops"),
    "00:15:C5": ("Dell", "desktops"),
    "00:16:F0": ("Dell", "desktops"),
    "00:18:8B": ("Dell", "desktops"),
    "00:19:B9": ("Dell", "desktops"),
    "00:1A:A0": ("Dell", "desktops"),
    "00:1C:23": ("Dell", "desktops"),
    "00:1D:09": ("Dell", "desktops"),
    "00:1E:4F": ("Dell", "desktops"),
    "00:1E:C9": ("Dell", "desktops"),
    "00:21:70": ("Dell", "desktops"),
    "00:21:9B": ("Dell", "desktops"),
    "00:22:19": ("Dell", "desktops"),
    "00:23:AE": ("Dell", "desktops"),
    "00:24:E8": ("Dell", "desktops"),
    "00:25:64": ("Dell", "desktops"),
    "00:26:B9": ("Dell", "desktops"),
    "14:18:77": ("Dell", "desktops"),
    "14:58:D0": ("Dell", "desktops"),
    "14:B3:1F": ("Dell", "desktops"),
    "14:FE:B5": ("Dell", "desktops"),
    "18:03:73": ("Dell", "desktops"),
    "18:66:DA": ("Dell", "desktops"),
    "18:A9:9B": ("Dell", "desktops"),
    "18:DB:F2": ("Dell", "desktops"),
    "1C:40:24": ("Dell", "desktops"),
    "24:6E:96": ("Dell", "desktops"),
    "24:B6:FD": ("Dell", "desktops"),
    "28:F1:0E": ("Dell", "desktops"),
    "34:17:EB": ("Dell", "desktops"),
    "34:E6:D7": ("Dell", "desktops"),
    "3C:2A:F4": ("Dell", "desktops"),
    "44:A8:42": ("Dell", "desktops"),
    "4C:76:25": ("Dell", "desktops"),
    "50:9A:4C": ("Dell", "desktops"),
    "54:9F:35": ("Dell", "desktops"),
    "5C:26:0A": ("Dell", "desktops"),
    "5C:F9:DD": ("Dell", "desktops"),
    "64:00:6A": ("Dell", "desktops"),
    "74:86:7A": ("Dell", "desktops"),
    "74:E6:E2": ("Dell", "desktops"),
    "78:2B:CB": ("Dell", "desktops"),
    "78:45:C4": ("Dell", "desktops"),
    "7C:2A:31": ("Dell", "desktops"),
    "80:18:44": ("Dell", "desktops"),
    "84:7B:EB": ("Dell", "desktops"),
    "84:8F:69": ("Dell", "desktops"),
    "90:B1:1C": ("Dell", "desktops"),
    "98:40:BB": ("Dell", "desktops"),
    "98:90:96": ("Dell", "desktops"),
    "A4:1F:72": ("Dell", "desktops"),
    "A4:BA:DB": ("Dell", "desktops"),
    "B0:83:FE": ("Dell", "desktops"),
    "B4:E1:0F": ("Dell", "desktops"),
    "B8:2A:72": ("Dell", "desktops"),
    "B8:AC:6F": ("Dell", "desktops"),
    "B8:CA:3A": ("Dell", "desktops"),
    "BC:30:5B": ("Dell", "desktops"),
    "C8:1F:66": ("Dell", "desktops"),
    "D0:43:1E": ("Dell", "desktops"),
    "D0:67:E5": ("Dell", "desktops"),
    "D4:81:D7": ("Dell", "desktops"),
    "D4:BE:D9": ("Dell", "desktops"),
    "E0:DB:55": ("Dell", "desktops"),
    "E4:43:4B": ("Dell", "desktops"),
    "E8:B1:FC": ("Dell", "desktops"),
    "EC:F4:BB": ("Dell", "desktops"),
    "F0:1F:AF": ("Dell", "desktops"),
    "F4:8E:38": ("Dell", "desktops"),
    "F8:B1:56": ("Dell", "desktops"),
    "F8:BC:12": ("Dell", "desktops"),
    "F8:CA:B8": ("Dell", "desktops"),

    # Lenovo (laptops)
    "00:06:1B": ("Lenovo", "laptops"),
    "00:09:2D": ("Lenovo", "laptops"),
    "00:0A:E4": ("Lenovo", "laptops"),
    "00:12:FE": ("Lenovo", "laptops"),
    "00:1A:6B": ("Lenovo", "laptops"),
    "00:21:CC": ("Lenovo", "laptops"),
    "28:D2:44": ("Lenovo", "laptops"),
    "34:02:86": ("Lenovo", "laptops"),
    "50:7B:9D": ("Lenovo", "laptops"),
    "54:E1:AD": ("Lenovo", "laptops"),
    "6C:C2:17": ("Lenovo", "laptops"),
    "70:5A:0F": ("Lenovo", "laptops"),
    "74:70:FD": ("Lenovo", "laptops"),
    "98:FA:9B": ("Lenovo", "laptops"),
    "C8:DD:C9": ("Lenovo", "laptops"),
    "D8:FC:93": ("Lenovo", "laptops"),
    "E8:2A:44": ("Lenovo", "laptops"),
    "F0:03:8C": ("Lenovo", "laptops"),

    # OnePlus (mobiles)
    "94:65:2D": ("OnePlus", "mobiles"),
    "C0:EE:40": ("OnePlus", "mobiles"),

    # Google Pixel
    "3C:28:6D": ("Google Pixel", "mobiles"),

    # Motorola (mobiles)
    "00:08:0E": ("Motorola", "mobiles"),
    "00:0A:28": ("Motorola", "mobiles"),
    "00:0C:E5": ("Motorola", "mobiles"),
    "00:11:1A": ("Motorola", "mobiles"),
    "00:11:AE": ("Motorola", "mobiles"),
    "00:12:25": ("Motorola", "mobiles"),
    "00:14:04": ("Motorola", "mobiles"),
    "00:17:00": ("Motorola", "mobiles"),
    "00:18:C0": ("Motorola", "mobiles"),
    "00:1A:1E": ("Motorola", "mobiles"),
    "00:1A:66": ("Motorola", "mobiles"),
    "00:1B:DD": ("Motorola", "mobiles"),
    "00:1C:12": ("Motorola", "mobiles"),
    "00:1D:6E": ("Motorola", "mobiles"),
    "00:1E:5A": ("Motorola", "mobiles"),
    "00:22:CE": ("Motorola", "mobiles"),
    "00:24:37": ("Motorola", "mobiles"),
    "00:25:F2": ("Motorola", "mobiles"),
    "00:50:C2": ("Motorola", "mobiles"),
    "1C:56:FE": ("Motorola", "mobiles"),
    "60:BE:B5": ("Motorola", "mobiles"),
    "68:C4:4D": ("Motorola", "mobiles"),
    "80:6C:1B": ("Motorola", "mobiles"),
    "9C:2E:A1": ("Motorola", "mobiles"),
    "CC:C3:EA": ("Motorola", "mobiles"),
    "D8:B0:4C": ("Motorola", "mobiles"),

    # ASUS (laptops/network)
    "00:0C:6E": ("ASUS", "network"),
    "00:0E:A6": ("ASUS", "network"),
    "00:11:D8": ("ASUS", "desktops"),
    "00:13:D4": ("ASUS", "desktops"),
    "00:15:F2": ("ASUS", "desktops"),
    "00:17:31": ("ASUS", "desktops"),
    "00:18:F3": ("ASUS", "desktops"),
    "00:1A:92": ("ASUS", "desktops"),
    "00:1B:FC": ("ASUS", "desktops"),
    "00:1D:60": ("ASUS", "desktops"),
    "00:1E:8C": ("ASUS", "desktops"),
    "00:1F:C6": ("ASUS", "desktops"),
    "00:22:15": ("ASUS", "desktops"),
    "00:23:54": ("ASUS", "desktops"),
    "00:24:8C": ("ASUS", "desktops"),
    "00:26:18": ("ASUS", "desktops"),
    "04:92:26": ("ASUS", "desktops"),
    "08:60:6E": ("ASUS", "desktops"),
    "10:7B:44": ("ASUS", "desktops"),
    "14:DA:E9": ("ASUS", "desktops"),
    "1C:87:2C": ("ASUS", "desktops"),
    "20:CF:30": ("ASUS", "desktops"),
    "2C:4D:54": ("ASUS", "desktops"),
    "2C:56:DC": ("ASUS", "network"),
    "30:85:A9": ("ASUS", "desktops"),
    "38:D5:47": ("ASUS", "desktops"),
    "3C:97:0E": ("ASUS", "desktops"),
    "40:16:7E": ("ASUS", "desktops"),
    "48:5B:39": ("ASUS", "desktops"),
    "4C:ED:FB": ("ASUS", "desktops"),
    "50:46:5D": ("ASUS", "desktops"),
    "54:04:A6": ("ASUS", "desktops"),
    "60:45:CB": ("ASUS", "desktops"),
    "6C:B0:CE": ("ASUS", "desktops"),
    "70:8B:CD": ("ASUS", "desktops"),
    "74:D0:2B": ("ASUS", "desktops"),
    "78:24:AF": ("ASUS", "desktops"),
    "88:D7:F6": ("ASUS", "desktops"),
    "90:E6:BA": ("ASUS", "desktops"),
    "AC:22:0B": ("ASUS", "desktops"),
    "B0:6E:BF": ("ASUS", "desktops"),
    "BC:EE:7B": ("ASUS", "desktops"),
    "C8:60:00": ("ASUS", "network"),
    "D4:5D:64": ("ASUS", "desktops"),
    "E0:3F:49": ("ASUS", "desktops"),
    "F0:79:59": ("ASUS", "desktops"),
    "F4:6D:04": ("ASUS", "desktops"),
    "FC:C2:33": ("ASUS", "desktops"),

    # Espressif (IoT - ESP32/ESP8266)
    "24:0A:C4": ("Espressif", "iot"),
    "24:6F:28": ("Espressif", "iot"),
    "24:B2:DE": ("Espressif", "iot"),
    "2C:3A:E8": ("Espressif", "iot"),
    "30:AE:A4": ("Espressif", "iot"),
    "3C:61:05": ("Espressif", "iot"),
    "3C:71:BF": ("Espressif", "iot"),
    "40:F5:20": ("Espressif", "iot"),
    "48:3F:DA": ("Espressif", "iot"),
    "4C:11:AE": ("Espressif", "iot"),
    "54:43:B2": ("Espressif", "iot"),
    "5C:CF:7F": ("Espressif", "iot"),
    "60:01:94": ("Espressif", "iot"),
    "68:C6:3A": ("Espressif", "iot"),
    "7C:9E:BD": ("Espressif", "iot"),
    "80:7D:3A": ("Espressif", "iot"),
    "84:0D:8E": ("Espressif", "iot"),
    "84:CC:A8": ("Espressif", "iot"),
    "84:F3:EB": ("Espressif", "iot"),
    "8C:AA:B5": ("Espressif", "iot"),
    "90:97:D5": ("Espressif", "iot"),
    "94:B5:55": ("Espressif", "iot"),
    "94:B9:7E": ("Espressif", "iot"),
    "98:CD:AC": ("Espressif", "iot"),
    "98:F4:AB": ("Espressif", "iot"),
    "A0:20:A6": ("Espressif", "iot"),
    "A4:7B:9D": ("Espressif", "iot"),
    "A4:CF:12": ("Espressif", "iot"),
    "AC:67:B2": ("Espressif", "iot"),
    "B4:E6:2D": ("Espressif", "iot"),
    "BC:DD:C2": ("Espressif", "iot"),
    "C4:4F:33": ("Espressif", "iot"),
    "C8:2B:96": ("Espressif", "iot"),
    "CC:50:E3": ("Espressif", "iot"),
    "D8:A0:1D": ("Espressif", "iot"),
    "DC:4F:22": ("Espressif", "iot"),
    "E0:98:06": ("Espressif", "iot"),
    "E8:DB:84": ("Espressif", "iot"),
    "EC:FA:BC": ("Espressif", "iot"),
    "F0:08:D1": ("Espressif", "iot"),
    "F4:CF:A2": ("Espressif", "iot"),

    # Tuya (IoT - smart home)
    "D8:1F:12": ("Tuya", "iot"),
    "10:D5:61": ("Tuya", "iot"),

    # Polycom/Poly (VoIP)
    "00:04:F2": ("Polycom", "voip"),
    "00:19:1A": ("Polycom", "voip"),
    "00:E0:DB": ("Polycom", "voip"),
    "64:16:7F": ("Polycom", "voip"),

    # Yealink (VoIP)
    "00:15:65": ("Yealink", "voip"),
    "80:5E:C0": ("Yealink", "voip"),
    "80:5E:C0": ("Yealink", "voip"),

    # Grandstream (VoIP)
    "00:0B:82": ("Grandstream", "voip"),

    # Aruba Networks
    "00:0B:86": ("Aruba", "network"),
    "00:1A:1E": ("Aruba", "network"),
    "00:24:6C": ("Aruba", "network"),
    "04:BD:88": ("Aruba", "network"),
    "20:4C:03": ("Aruba", "network"),
    "24:DE:C6": ("Aruba", "network"),
    "40:E3:D6": ("Aruba", "network"),
    "6C:F3:7F": ("Aruba", "network"),
    "84:D4:7E": ("Aruba", "network"),
    "94:B4:0F": ("Aruba", "network"),
    "9C:1C:12": ("Aruba", "network"),
    "AC:A3:1E": ("Aruba", "network"),
    "D8:C7:C8": ("Aruba", "network"),

    # Fitbit (smart watches)
    "C0:1B:38": ("Fitbit", "smart_watches"),
    "E4:33:AE": ("Fitbit", "smart_watches"),
}

# Device categories with display info
DEVICE_CATEGORIES = {
    "cameras": {"name": "Cameras", "icon": "fa-video-camera", "color": "#e74c3c"},
    "desktops": {"name": "Desktops", "icon": "fa-desktop", "color": "#3498db"},
    "gaming_consoles": {"name": "Gaming Consoles", "icon": "fa-gamepad", "color": "#e67e22"},
    "iot": {"name": "IoT Devices", "icon": "fa-microchip", "color": "#2ecc71"},
    "laptops": {"name": "Laptops", "icon": "fa-laptop", "color": "#9b59b6"},
    "mobiles": {"name": "Mobile Devices", "icon": "fa-mobile", "color": "#1abc9c"},
    "multimedia": {"name": "Multimedia", "icon": "fa-play-circle", "color": "#f39c12"},
    "network": {"name": "Network Equipment", "icon": "fa-sitemap", "color": "#34495e"},
    "printers": {"name": "Printers", "icon": "fa-print", "color": "#95a5a6"},
    "servers": {"name": "Servers", "icon": "fa-server", "color": "#2c3e50"},
    "smart_glasses": {"name": "Smart Glasses", "icon": "fa-eye", "color": "#8e44ad"},
    "smart_watches": {"name": "Smart Watches", "icon": "fa-clock-o", "color": "#16a085"},
    "tvs": {"name": "Smart TVs", "icon": "fa-television", "color": "#c0392b"},
    "vehicles": {"name": "Vehicles", "icon": "fa-car", "color": "#27ae60"},
    "voip": {"name": "VoIP Phones", "icon": "fa-phone", "color": "#2980b9"},
    "other": {"name": "Other", "icon": "fa-question-circle", "color": "#7f8c8d"},
}


# Hostname pattern -> category mapping
HOSTNAME_PATTERNS = {
    "iphone": "mobiles",
    "ipad": "mobiles",
    "ipod": "mobiles",
    "android": "mobiles",
    "galaxy": "mobiles",
    "pixel": "mobiles",
    "oneplus": "mobiles",
    "huawei": "mobiles",
    "xiaomi": "mobiles",
    "redmi": "mobiles",
    "oppo": "mobiles",
    "vivo": "mobiles",
    "macbook": "laptops",
    "thinkpad": "laptops",
    "surface": "laptops",
    "chromebook": "laptops",
    "laptop": "laptops",
    "notebook": "laptops",
    "imac": "desktops",
    "desktop": "desktops",
    "workstation": "desktops",
    "tower": "desktops",
    "xbox": "gaming_consoles",
    "playstation": "gaming_consoles",
    "ps4": "gaming_consoles",
    "ps5": "gaming_consoles",
    "nintendo": "gaming_consoles",
    "switch": "gaming_consoles",
    "chromecast": "multimedia",
    "firetv": "multimedia",
    "fire-tv": "multimedia",
    "roku": "multimedia",
    "appletv": "multimedia",
    "apple-tv": "multimedia",
    "sonos": "multimedia",
    "echo": "iot",
    "alexa": "iot",
    "home-mini": "iot",
    "google-home": "iot",
    "nest": "iot",
    "ring": "cameras",
    "camera": "cameras",
    "cam": "cameras",
    "ipcam": "cameras",
    "printer": "printers",
    "epson": "printers",
    "canon": "printers",
    "hp-printer": "printers",
    "brother": "printers",
    "samsung-tv": "tvs",
    "lg-tv": "tvs",
    "smart-tv": "tvs",
    "smarttv": "tvs",
    "vizio": "tvs",
    "tesla": "vehicles",
    "server": "servers",
    "nas": "servers",
    "synology": "servers",
    "qnap": "servers",
    "raspberry": "iot",
    "raspberrypi": "iot",
    "esp32": "iot",
    "esp8266": "iot",
    "tasmota": "iot",
    "shelly": "iot",
    "tuya": "iot",
    "smartplug": "iot",
    "thermostat": "iot",
    "fitbit": "smart_watches",
    "garmin": "smart_watches",
    "apple-watch": "smart_watches",
}


def lookup_oui(mac: str) -> tuple:
    """Look up vendor and device category from MAC address OUI prefix.

    Args:
        mac: MAC address (any format with : or - separators)

    Returns:
        (vendor_name, device_category) or ("Unknown", "other")
    """
    mac = mac.upper().replace("-", ":").strip()
    prefix = mac[:8]  # e.g., "00:11:22"
    entry = OUI_VENDOR_MAP.get(prefix)
    if entry:
        return entry
    return ("Unknown", "other")


def detect_category(mac: str, hostname: str = "") -> str:
    """Detect device category using OUI lookup + hostname pattern matching.

    Args:
        mac: MAC address
        hostname: Device hostname (optional)

    Returns:
        Device category string
    """
    # First try OUI lookup
    _, category = lookup_oui(mac)

    # If OUI gave us something specific, use it
    if category != "other":
        return category

    # Fall back to hostname pattern matching
    if hostname:
        hostname_lower = hostname.lower()
        for pattern, cat in HOSTNAME_PATTERNS.items():
            if pattern in hostname_lower:
                return cat

    return category
